name: Bug report
description: Report a problem in PAM Shop repo
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue
      placeholder: Steps to reproduce...
    validations:
      required: true
